/* This file is autogenerated, do not edit*/
#include "testqtpong_automoc.dir/moc_engine_KJWSEL5MH53XEC.cpp"
#include "testqtpong_automoc.dir/moc_mainwindow_L2CLFKCLUYECYY.cpp"
#include "testqtpong_automoc.dir/moc_qtpong_HX7YA3TSSWABXP.cpp"
